---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/jul09mrd/public_html/mrrobot
    - /bin/cp -r * $DEPLOYPATH #copy all from root
   # - /bin/cp -r ./public/* $DEPLOYPATH/public_html/
  #  - /bin/cp ./public/js/*.js $DEPLOYPATH/public_html/js
  # - /bin/cp ./public/css/*.css $DEPLOYPATH/public_html/css